### ISSUE TITLE
Problem with changing FLUKA .inp

### ISSUE THREAD

**Issue by GordoNice** [DataMedSci/mcpartools#192]
Hello! First, want to thank you for this tool! But, found some troubles regarding to changing seed number and number of particles in FLUKA input file. The problem in this part of code of the mcpartools/mcpartools/mcengine/fluka.py file:

    def randomize(self, new_seed):
        result = []
        # TODO think of using flair API for that purpose
        for l in self.input_lines:
            # TODO better discovery needed
            if l.startswith("RANDOMIZ"):
                # TODO check formatting
                new_line = "RANDOMIZ         1.0 {0:f}\n".format(new_seed)
                logger.debug("Replace RAND line with [" + new_line[:-1] + "]")
                result.append(new_line)
            else:
                result.append(l)
        self.input_lines = result

    def set_particle_no(self, particle_no):
        result = []
        for l in self.input_lines:
            # TODO better discovery needed
            if l.startswith("START"):
                # TODO check formatting
                new_line = "START        {0:10.1f}\n".format(particle_no)
                result.append(new_line)
                logger.debug("Replace START line with [" + new_line[:-1] + "]")
            else:
                result.append(l)
        self.input_lines = result

To be more concrete in these lines:

    new_line = "RANDOMIZ         1.0 {0:f}\n".format(new_seed)
    logger.debug("Replace RAND line with [" + new_line[:-1] + "]")

    new_line ="START        {0:10.1f}\n".format(particle_no)
    result.append(new_line)

It works fine, if number of particles about 10000 and number of jobs less than 100. But, if one wants to increase number of particles, lets say about 100000, so appends one more zero and than input consider this as 1e4 instead of 1e5! And also if number of jobs higher than 100, lets say 500, only 100 input files will work! Because others cause problems during FLUKA run, FLUKA just cant read these inputs right, because its not aligned right. So this part of code should be more flexible. I tried to do something, but for now no luck, because I need to look on code in general, but dont have enough time for that. So can you please do something with this? To make it work with every particle number and higher numder of jobs.

Thank you in advance!

**Comment by grzanka** [comment]
Thank you for spotting this problem. I will fix it this week and make a new release !

**Comment by GordoNice** [comment]
> Thank you for spotting this problem. I will fix it this week and make a new release !

Thanks! Now I found kind of solution using this line: 
`new_line = "RANDOMIZ          1.    {0}\n".format(str(new_seed+10000)+".")`
Works okay if number of jobs less than 10000, but this is shit code still.
And for particle number I am using:
`new_line = "START        {0}\n".format(str(particle_no)+'.')`
 Works only for number of particles with 1e5, which is suitable for me, but still shit code and the solution must work on every case. 

A bit off topic: I wanted to ask, what if I need to generate the same number of jobs on the second time? I mean the first time, for example, generated 200 copies of initial input with some seeds, after they launched and finished, I want to launch another 200 copies, so, I generate 200 one more time and can launch them again, but! Seeds will be the same! So, I will get the same result! Quick solution I found just change my shit code again like that:
`new_line = "RANDOMIZ          1.    {0}\n".format(str(new_seed+10000)+".")` - for first run
`new_line = "RANDOMIZ          1.    {0}\n".format(str(new_seed+20000)+".")` - for second run
`new_line = "RANDOMIZ          1.    {0}\n".format(str(new_seed+30000)+".")` - for third run
and so on... Till I get good statistics, and seeds will be unique. It is important, because sometimes you dont have enough CPU to launch 400 at once and you need to divide on 200 at first and 200 after.

**Comment by grzanka** [comment]
I've prepared a simple fix, available here:
https://github.com/DataMedSci/mcpartools/pull/193/files

Now I am testing it and will merge it soon.

The problem was related to amount of whitespace between non-white characters.

Adding a special line as in Fluka documentation:
http://www.fluka.org/content/manuals/online/RANDOMIZ.html
helps a bit.

Each field with number should span for 10 characters and be correctly positioned - it is a relict from Fortran punched card era:
![image](https://user-images.githubusercontent.com/7374733/53429050-2954d000-39ec-11e9-9960-93b38fea5ef5.png)

**Comment by grzanka** [comment]
As for your second question - this would be another feature to implement, but there is simpler workaround.

1. Generate 400 jobs at once, but do not submit them.
2. Try to locate generated `submit.sh` script. Around line 14 you will find sth similar to:
```
PROCESS_CMD="sbatch (...) --array=1-400
```

Replace `1-400` with `1-200` and submit the jobs (run submit.sh script). This will submit first 200 with seeds from 1 to 200.

Then replace `1-200` with `201-400` which will submit a second part.

**Comment by grzanka** [comment]
@GordoNice new version is ready for testing: https://pypi.org/project/mcpartools/#history
Try to update your mcpartools installation via `pip install -U mcpartools` and check if the problem persists.

**Comment by GordoNice** [comment]
> @GordoNice new version is ready for testing: https://pypi.org/project/mcpartools/#history
> Try to update your mcpartools installation via `pip install -U mcpartools` and check if the problem persists.

Seems its working now, at least FLUKA understands the input, but I think its not necessary appending this all the time (see pic). Its not usefull at all and also takes much more execution time.
![2019-02-26-211247_1547x845_scrot](https://user-images.githubusercontent.com/19708620/53436218-c2471380-3a0b-11e9-886f-b58beb04d43f.png)
I think it will be fine for seeds if they not  (and _usually not_)

> span for 10 characters

Like you mentioned before, but still, number of particles can be larger, and if I want to launch 138000000 particles, for example, which is not so big number, it will cause trouble again:
![2019-02-26-212753_1547x845_scrot](https://user-images.githubusercontent.com/19708620/53437228-12bf7080-3a0e-11e9-8488-959ff7e8b292.png)

So, solution should be more flexible again, in Flair, which is interface for FLUKA, when you type so large number its start to use e-notation, so, maybe its better to use e-notation also, if the amount of chars are bigger than 10.

**Comment by grzanka** [comment]
Thank you for this remarks - I will adapt the code accordingly.

**Comment by grzanka** [comment]
@GordoNice please try upgrading again. Necessary fixes were introduced in PR #194

**Comment by GordoNice** [comment]
@grzanka now it seems works fine! Thanks again for very useful tool!

**Comment by grzanka** [comment]
@GordoNice thank you for submitting this issue ! In case of any other problems I will be glad to help. I'd also like to advertise some other projects, like https://pymchelper.readthedocs.io/en/stable/

**Comment by GordoNice** [comment]
@grzanka no problems and for sure I will let you know if some troubles will occur! Thanks for ad, seems also interesting, but depends on particular case, for now I like to make my own scripts to process output data =)
