### ISSUE TITLE
Add support for parallelizing SHIELD-HIT12A jobs

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/mcpartools#38]
Specifying number of particles and RNG seed is done by cmd line switches (see `shieldhit --help`) and doesn't require modification of input files.

Specification of output files is done by setting different workspace by cmd line switch.

Input files are also specified via cmd line (one-by-one or as a directory).

**Comment by ant6** [comment]
Ok, so I looked at `shieldhit` installed on Prometheus and got this (with `--help`):
```
  -n, --nstat=NUM        Override NSTAT using NUM amount of particles instead.
                         Useful for testing with short runs or dry runs, -n0.
  -N, --seedoffset=NUM   Add NUM to the random seed. Max 9999.

  -b, --beamfile=FILE    Load FILE instead of WORKDIR/beam.dat
  -g, --geofile=FILE     Load FILE instead of WORKDIR/geo.dat
  -m, --matfile=FILE     Load FILE instead of WORKDIR/mat.dat
  -d, --detectfile=FILE  Load FILE instead of WORKDIR/detect.dat
```
in `generatemc.py` we have:
```py
    parser.add_argument('-s', '--scheduler_options',
                        type=str,
                        default=None,
                        help='optional scheduler options path to file or list of options in square brackets')
```
and in `run_shieldhit.sh`:
```sh
$SHIELDHIT_BIN --beamfile=$BEAM_FILE --geofile=$GEO_FILE --matfile=$MAT_FILE --detectfile=$DETECT_FILE -n $PARTICLE_NO -N $RNG_SEED $WORK_DIR
```

@grzanka I think, I need more info on this task, because it seems it's already done or partially done.

**Comment by grzanka** [comment]
I think that automatic discovery based on input files is sufficient. What we could do is to add better error handling if wrong input file is provided (i.e. .avi file). Extra switches is not needed.

Try to play with SH simulation using mcpartools - run several simulations on prometheus cluster. Try to simulate how users would behave.

**Comment by ant6** [comment]
Similar to #59

**Comment by ant6** [comment]
@grzanka How about we make symbolic links in destination/created directories to source files (*.dat, .txt, whatever we have in WORK_DIR)?

**Comment by grzanka** [comment]
Let us move discussion to #59

**Comment by grzanka** [comment]
I think that once #59 is completed, then this task can be closed
