### ISSUE TITLE
Fix failing sphinx build

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/mcpartools#45]
Problem seen here:
https://travis-ci.org/DataMedSci/mcpartools/jobs/182812557

Related to https://github.com/DataMedSci/beprof/issues/118

Can be fixed as here:
https://github.com/DataMedSci/beprof/pull/110/commits/6fcd583b0e89eea9ee8b23d8189bc6e7c5f1c09c

**Comment by grzanka** [comment]
@ant6 can you take a look ?

**Comment by ant6** [comment]
@grzanka should I also change Python version for docs build?
