### ISSUE TITLE
Test if version 0.1.5 is successully deployed

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/mcpartools#47]

**Comment by grzanka** [comment]
@ant6 can you take a look on https://travis-ci.org/DataMedSci/mcpartools/builds/184221147 ?

**Comment by ant6** [comment]
@grzanka Build #202 passed.

**Comment by ant6** [comment]
@grzanka it went well, I think: https://pypi.python.org/pypi/mcpartools here's 1.5
